services:
  httpd:
    build:
      context: .
      dockerfile: ./container-files/Containerfile_httpd-${HTTPD_VERSION:-latest}
    container_name: "httpd"
    volumes:
      - ./box:/var/www:Z
    ports:
      - ${HTTPD_PORT:-8080}:80
