services:
    pgsql:
        image: postgres:${POSTGRES_VERSION}
        container_name: "pgsql"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - postgres-data-${POSTGRES_VERSION}:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT:-5432}:5432

    php:
        build:
            context: .
            dockerfile: ./container-files/Containerfile_php-${PHP_VERSION:-latest}
        container_name: "php"
        volumes:
            - ./box:/var/www:z
        expose:
            - ${PHP_PORT:-9000}
        depends_on:
            - pgsql

    httpd:
        build:
            context: .
            dockerfile: ./container-files/Containerfile_httpd-${HTTPD_VERSION:-latest}
        container_name: "httpd"
        volumes:
            - ./box:/var/www:z
        ports:
            - ${HTTPD_PORT:-8080}:80
        depends_on:
            - php

volumes:
    postgres-data-${POSTGRES_VERSION}:
