#   Imagen
FROM httpd:latest

#   Actualizar el sistema
RUN apt update && \
    apt install vim curl -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

#   Copiar la configuración inicial
COPY config/httpd/extra/httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf
COPY config/httpd/httpd.conf /usr/local/apache2/conf/httpd.conf
